name: temp

on: [push, pull_request]

jobs:
  temp:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '3.6', 'pypy-3.6', 'pypy-3.7' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install isort black flake8 pytest
          fi

      - name: Check test status with a conditional
        run: |
          flake8 .
          pytest --cov --cov-fail-under=79
          if [ "${{ github.event_name }}" = 'release' ]; then
            pytest .
          fi