name: temp

on: [push, pull_request]

jobs:
  temp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install isort black flake8 mypy pytest

      - name: Check test status
        - run: pipenv run isort --recursive --diff
        - run: pipenv run black --check .
        - run: pipenv run flake8
        - run: pipenv run mypy
        - run: pipenv run pytest --cov --cov-fail-under=100