name: temp

on: [push, pull_request]

jobs:
  temp:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy-2.7', 'pypy-3.6', 'pypy-3.7' ]
      name: Python ${{ matrix.python-version }} temp
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install isort black flake8 pytest

      - name: Check test status with a conditional
        run: |
          pipenv lock --pre --clear
          pipenv run isort --recursive --diff
          pipenv run black --check --diff .
          pipenv run flake8
          pipenv run pytest --cov --cov-fail-under=79
          if [ "${{ github.event_name }}" = 'release' ]; then
              pipenv run pytest tests/
          fi